// Generated by CoffeeScript 1.6.2
(function() {
  var commands, ribbit;

  commands = require("./commands");

  ribbit = require("ribbit");

  exports.run = function(source, context, next) {
    return exports.load().run(source, context, next);
  };

  exports.load = function(context, next) {
    return ribbit.run(commands, context, next);
  };

}).call(this);
