// Generated by CoffeeScript 1.6.2
(function() {
  var flatstack, fs, mkdirp, outcome, path;

  fs = require("fs");

  path = require("path");

  mkdirp = require("mkdirp");

  flatstack = require("flatstack");

  outcome = require("outcome");

  module.exports = {
    "def copy": {
      "run": function(context, next) {
        var baseDir, callstack, input, output, process, stat,
          _this = this;

        input = context.get("input");
        output = context.get("output");
        baseDir = context.get("baseDir");
        process = context.get("processContent");
        if (baseDir) {
          baseDir = path.normalize(baseDir);
        }
        stat = fs.statSync(input);
        if (stat.isDirectory()) {
          return mkdirp(output, function() {
            return next();
          });
        }
        callstack = flatstack();
        callstack.push(function() {
          return mkdirp(path.dirname(output), callstack.pause().resume);
        });
        callstack.push(function() {
          var content;

          content = fs.readFileSync(input);
          context.set("content", content);
          if (process) {
            return _this.run(process, context, callstack.pause().resume);
          }
        });
        return callstack.push(function() {
          return fs.writeFile(context.get("output"), context.get("content"), next);
        });
      }
    }
  };

}).call(this);
