// Generated by CoffeeScript 1.6.2
(function() {
  var fs;

  fs = require("fs");

  module.exports = fs.readdirSync(__dirname).filter(function(file) {
    return !/.DS_Store|index/.test(file);
  }).map(function(file) {
    return require(__dirname + "/" + file);
  });

}).call(this);
