// Generated by CoffeeScript 1.6.2
(function() {
  module.exports = {
    "def run": {
      "run": function(context, next) {
        return this.all.run(context.get("value"), next);
      }
    }
  };

}).call(this);
